//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_Phat
    {
        public int MaNhanVien { get; set; }
        public int MaPhat { get; set; }
        public System.DateTime Ngay { get; set; }
    
        public virtual LoaiPhat LoaiPhat { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
