//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ct_Thuong
    {
        [DisplayName("Mã chi tiết thưởng")]
        public int MaCTThuong { get; set; }
        [DisplayName("Mã nhân viên")]
        public int MaNhanVien { get; set; }
        [DisplayName("Mã loại thưởng")]
        public int MaLoaiThuong { get; set; }


        [DisplayName("Người thưởng")]
        public string NguoiThuong { get; set; }
        [DisplayName("Ngày thưởng")]
        public System.DateTime NgayThuong { get; set; }
        [DisplayName("Trạng thái")]
        public bool TrangThai { get; set; }
        [DisplayName("Người sửa")]
        public string NguoiSua { get; set; }
        [DisplayName("Ngày sửa")]
        public System.DateTime NgaySua { get; set; }
        public bool IsChecked { get; set; }



        public virtual NhanVien NhanVien { get; set; }
        public virtual LoaiThuong LoaiThuong { get; set; }
    }
}
