//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_Thuong
    {
        public int MaCT_Thuong { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> MaThuong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual LoaiThuong LoaiThuong { get; set; }
    }
}
