//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNS_1Entities : DbContext
    {
        public QLNS_1Entities()
            : base("name=QLNS_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoHiem> BaoHiems { get; set; }
        public virtual DbSet<ChamCong> ChamCongs { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<Ct_Phat> Ct_Phat { get; set; }
        public virtual DbSet<Ct_Thuong> Ct_Thuong { get; set; }
        public virtual DbSet<LoaiPhat> LoaiPhats { get; set; }
        public virtual DbSet<LoaiThuong> LoaiThuongs { get; set; }
        public virtual DbSet<LuongCoBan> LuongCoBans { get; set; }
        public virtual DbSet<LuongThang> LuongThangs { get; set; }
        public virtual DbSet<Nghi> Nghis { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
