//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        public int MaNhanVien { get; set; }
        [Required(ErrorMessage = "Tên tài khoản không được trống...")]
        public string TenTK { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được trống...")]
        public string MatKhau { get; set; }
        public int MaQuyen { get; set; }
        public string ResetPasswordCode { get; set; }


        public virtual NhanVien NhanVien { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
