//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [DisplayName("Mã nhân viên")]
        public int MaNhanVien { get; set; }
        [DisplayName("Tên tài khoản")]
        [Required(ErrorMessage = "Tên tài khoản không được trống...")]
        public string TenTK { get; set; }
        [DisplayName("Mật khẩu")]

        [Required(ErrorMessage = "Mật khẩu không được trống...")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*\d).{5,25}$", ErrorMessage = "Mật khẩu bao gồm chữ và số, từ 5 đến 25 kí tự")]
        public string MatKhau { get; set; }
        [DisplayName("Mã quyền")]
        public int MaQuyen { get; set; }
        public string ResetPasswordCode { get; set; }


        public virtual NhanVien NhanVien { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
